### ISSUE TITLE
Добавить typeguard на ErrorData из vk-bridge

### ISSUE THREAD

**Issue by dewolixgit** [ktsstudio/mediaproject-vk#16]
На одном из проектов использовалась такая штучка, позаимствовал из какого-то другого проекта, мне понравилась:
```typescript
import { ErrorData } from '@vkontakte/vk-bridge';

const VkErrorTypeSet = new Set<ErrorData['error_type']>([
  'client_error',
  'api_error',
  'auth_error',
]);

export const isVkError = (value: any): value is ErrorData => {
  return VkErrorTypeSet.has(value?.error_type);
};
```

Можно ещё добавить проверку на наличие обязательного поля `error_data` в тестируемом объекте:
`if ('error_data' in value) { ... }`

Может быть использована, например, перед проверкой на отказ пользователя, который тоже приходит в виде ошибки и принимает ErrorData:
```typescript
    try {
      await bridge.send(...);
    } catch (error) {
      if (!isVkError(error)) {
        return;
      }

      if (checkVkUserDenied(error)) {
        return;
      }
    }
```

**Comment by AliceSitedge** [comment]
Добавлено в версии 3.0.0
