### ISSUE TITLE
checkVkUserDenied: Добавить ещё один кейс обработки отказа пользователя

### ISSUE THREAD

**Issue by dewolixgit** [ktsstudio/mediaproject-vk#17]
При локальной разработке была замечена ещё одна ошибка, возникающая при отказе пользователя. На данный момент она не отлавливается в checkVkUserDenied

Условия, когда воспроизводится:
- Десктоп
- Локальная разработка
- Попытка шеринга в сниппет (с помощью функции shareVkPost) кастомной картинки (не из настроек приложения)
- Выстреливает и в открытом, и в закрытом для пользователей приле
- ВК Мини Аппам не выданы права на шеринг кастомной картинки

Так, получаю следующую ошибку от вк-бриджа:
```typescript
{
    "error_type": "client_error",
    "error_data": {
        "error_code": 10007,
        "error_reason": "Operation denied by user"
    }
}
```

![image](https://github.com/ktsstudio/mediaproject-vk/assets/71431554/90d048b5-b1d8-4fad-a4ee-c9bfec0dd32f)

Воспроизведение: https://drive.google.com/file/d/16YmW9KdzcOQVI1Eh7WJ2Y0GJgXPLo5CK/view?usp=sharing

**Comment by AliceSitedge** [comment]
Предлагаю в checkVkUserDenied просто на текст ошибки ориентироваться

**Comment by natalya-z** [comment]
> Предлагаю в checkVkUserDenied просто на текст ошибки ориентироваться

Там сейчас так и есть, но потом есть проверка на код ошибки 4

**Comment by AliceSitedge** [comment]
Исправлено в версии 3.0.0
